# Generated by Django 5.1.6 on 2025-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_interest_remove_customuser_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
